### ISSUE TITLE
Adding content

### ISSUE THREAD

**Issue by MrAppu** [D7EAD/resource#1]
How about adding more content like books and free resources in cybersecurity and also you can link the books using amazon affiliate program, or if you are not doing this for monetary purposes, free pdfs in sites like z library (https://b-ok.asia/) ?

**Comment by D7EAD** [comment]
I'd be glad to add links to books. However, linking sites that offer the books themselves can get sketchy. I'l leave it to the end-user to figure that out.

**Comment by MrAppu** [comment]
I have visited many sites and this is the only site (bok) legitimate I saw.
